CREATE TABLE IF NOT EXISTS SUPPLIER (
             SUPPLIERID INT NOT NULL AUTO_INCREMENT,
             NAME VARCHAR (255) NOT NULL,
             SHORTNAME VARCHAR (25) NOT NULL,
             EMAIL VARCHAR (50) NOT NULL,             
             PHONENUMBER VARCHAR (20) NOT NULL,
             PRIMARY KEY (SUPPLIERID)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS MEDICAL_ITEM (
             ITEMID INT NOT NULL AUTO_INCREMENT,
             `TYPE` VARCHAR (255) NOT NULL,
             NAME VARCHAR (255) NOT NULL,
             UNIT VARCHAR (50) NOT NULL,
             PRIMARY KEY (ITEMID),
             CONSTRAINT CHK_ITEM_TYPE CHECK (`TYPE` IN ('Device', 'Medicine'))
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS BENEFICIARY (
             BENEFICIARYID INT NOT NULL AUTO_INCREMENT,
             `NAME` VARCHAR (255) NOT NULL,
             SHORTNAME VARCHAR (20) NOT NULL,
             EMAIL VARCHAR (50) NOT NULL,             
             PHONENUMBER VARCHAR (20) NOT NULL,
             PRIMARY KEY (BENEFICIARYID)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS DONOR (
             DONORID INT NOT NULL AUTO_INCREMENT,
             ORGNAME VARCHAR (255) NOT NULL,
             ORGLINK VARCHAR (255) NOT NULL,
             EMAIL VARCHAR (50) NOT NULL,             
             PHONENUMBER VARCHAR (20) NOT NULL,
             PRIMARY KEY (DONORID)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS MEDICAL_NEED (
             NEEDID INT NOT NULL AUTO_INCREMENT,
             ITEMID INT NOT NULL,
             BENEFICIARYID INT NOT NULL,
             `PERIOD` TIMESTAMP NOT NULL,
             URGENCY VARCHAR (50) NOT NULL,
             PRIMARY KEY (NEEDID),
             FOREIGN KEY (ITEMID) REFERENCES MEDICAL_ITEM(ITEMID),
             CONSTRAINT CHK_NEED_URGENCY CHECK (`URGENCY` IN ('Normal', 'Critical', 'Urgent'))
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS QUOTATION (
             QUOTATIONID INT NOT NULL AUTO_INCREMENT,
             SUPPLIERID INT NOT NULL,
             ITEMID INT NOT NULL,
             BRANDNAME VARCHAR (50) NOT NULL,
             AVAILABLEQTY INT NOT NULL DEFAULT 0,
             `EXPIRYDATE` TIMESTAMP NOT NULL,
             UNITPRICE DECIMAL(15, 2) NOT NULL DEFAULT 0,
             REGULATORYINFO VARCHAR (100) NOT NULL,
             PRIMARY KEY (QUOTATIONID),
             FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(SUPPLIERID), 
             FOREIGN KEY (ITEMID) REFERENCES MEDICAL_ITEM(ITEMID)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS AID_PACKAGE (
             PACKAGEID INT NOT NULL AUTO_INCREMENT,
             NAME VARCHAR (20) NOT NULL,
             `DESCRIPTION` VARCHAR (1500) NOT NULL,
             `STATUS` VARCHAR (20) NOT NULL,
             PRIMARY KEY (PACKAGEID),
             CONSTRAINT CHK_PACKAGE_STATUS CHECK (`STATUS` 
             IN ('Draft', 'Published',
             	 'Awaiting Payment', 'Ordered', 'Shipped',
             	 'Received at MoH', 'Delivered'))
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS AID_PACKAGE_ITEM (
             PACKAGEITEMID INT NOT NULL AUTO_INCREMENT,
             QUOTATIONID INT NOT NULL,
             NEEDID INT NOT NULL,
             PACKAGEID INT NOT NULL,
             QTY INT NOT NULL DEFAULT 0,
             PRIMARY KEY (PACKAGEITEMID),
             FOREIGN KEY (QUOTATIONID) REFERENCES QUOTATION(QUOTATIONID),
             FOREIGN KEY (NEEDID) REFERENCES MEDICAL_NEED(NEEDID), 
             FOREIGN KEY (PACKAGEID) REFERENCES AID_PACKAGE(PACKAGEID)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS AID_PACKAGAE_UPDATE (
             PACKAGAEUPDATEID INT NOT NULL AUTO_INCREMENT,
             PACKAGEID INT NOT NULL,
             `UPDATE` VARCHAR (1500) NOT NULL,
             `DATE`  TIMESTAMP NOT NULL,
             PRIMARY KEY (PACKAGAEUPDATEID),
             FOREIGN KEY (PACKAGEID) REFERENCES AID_PACKAGE(PACKAGEID)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS PLEDGE (
             PLEDGEID INT NOT NULL AUTO_INCREMENT,
             PACKAGEID INT NOT NULL,
             DONORID INT NOT NULL,
             `STATUS` VARCHAR (20) NOT NULL,
             CONSTRAINT CHK_PLEDGE_STATUS CHECK (`STATUS` 
             IN ('Pledged', 'Payment Initiated', 'Payment Confirmed')),
             PRIMARY KEY (PLEDGEID),
             FOREIGN KEY (PACKAGEID) REFERENCES AID_PACKAGE(PACKAGEID),
             FOREIGN KEY (DONORID) REFERENCES DONOR(DONORID)
)ENGINE INNODB;

CREATE TABLE IF NOT EXISTS PLEDGE_UPDATE (
             PLEDGEUPDATEID INT NOT NULL AUTO_INCREMENT,
             PLEDGEID INT NOT NULL,
             `UPDATE` VARCHAR (1500) NOT NULL,
             `DATE`  TIMESTAMP NOT NULL,
             PRIMARY KEY (PLEDGEUPDATEID),
             FOREIGN KEY (PLEDGEID) REFERENCES PLEDGE(PLEDGEID)
)ENGINE INNODB;